---
:enable_log_auditor: "false"
:default_timeout: 3601
:operational_timeout: 3602
:terminated_timeout: 3603
:stopped_timeout: 3604
:completed_timeout: 3605
:inactive_timeout: 3606
:failed_timeout: 3607
:error_timeout: 3608
:snapshot_timeout: 3609
:booting_timeout: 3610
:grinder_subprocess: force_subprocess
:test_ordering: strict
:max_jobs: 2
:environment: testing
:colorized_text: show
:load_progress: show
:feature_mixins: spanning
:max_retries: 10
:throttling_values:
  "1":
    :max_instances: 1024
  "1956":
    :max_instances: 1024
  "1958":
    :max_instances: 1024
:test_permutation: exhaustive
:dns_domain: "dnsmadeeasy_new"
:dns_choice: "text:DNSMadeEasy"
