---
:enable_log_auditor: "false"
:default_timeout: 1200
:operational_timeout: 1200
:terminated_timeout: 1200
:stopped_timeout: 1200
:completed_timeout: 1200
:inactive_timeout: 1200
:failed_timeout: 1200
:error_timeout: 1200
:snapshot_timeout: 1200
:booting_timeout: 1200
:grinder_subprocess: force_subprocess
:test_ordering: strict
:max_jobs: 2
:environment: testing
:colorized_text: show
:load_progress: show
:feature_mixins: spanning
:max_retries: 10
:throttling_values:
  "1":
    :max_instances: 1024
  "1956":
    :max_instances: 12
  "1958":
    :max_instances: 12
:test_permutation: exhaustive
:dns_domain: "dnsmadeeasy_new"
:dns_choice: "text:DNSMadeEasy"
